# Generated by Django 2.0.2 on 2018-03-14 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authtools', '0003_auto_20160128_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('slug', models.UUIDField(blank=True, default=uuid.uuid4, editable=False)),
                ('email_verified', models.BooleanField(default=False, verbose_name='Email verified')),
                ('bio', models.CharField(blank=True, max_length=200, null=True, verbose_name='Short Bio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
